# This is a basic workflow to help you get started with Actions

name: CD production - Lambda

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: CI production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint **/*.py
  # This workflow contains a single job called "build"
  deploy:
    name: CD production - Lambda
    needs: test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: SET up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --target ./package -r requirement.txt
    # Runs a set of commands using the runners shell
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: generate ZIP
      run: |
        cd package && zip -r9 ${OLDPWD}/function.zip .
        cd $OLDPWD
        zip -g -r function.zip lambda_function.py api
    - name: Deploy Lambda
      run: |
        aws s3 cp function.zip s3://sperantitodeploy
        aws lambda update-function-code --function-name sperantito \
          --s3-bucket sperantitodeploy \
          --s3-key function.zip \
          --region us-east-2 \
          --no-publish
        aws lambda publish-version --function-name sperantito --region us-east-2
